IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10))




IF OBJECT_ID('TABLE_TESTE', 'U') IS NOT NULL

BEGIN
DROP TABLE TABLE_TESTE
END

create table TABLE_TESTE (ID VARCHAR(10))

