
DECLARE @IDADE INT
DECLARE @NOME VARCHAR(200)
DECLARE @DATA DATE

DECLARE @IDADE2 INT, @NOME2 VARCHAR(200), @DATA2 DATE

SET @IDADE = 20
--PRINT @IDADE

SET @NOME = 'JOÃO DA SILVA'
--PRINT @NOME

SET @DATA = '20180517'
--PRINT @DATA

DECLARE @CPF VARCHAR(12)
SET @CPF = '2600586709'

--SELECT NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES]
--WHERE CPF = @CPF

SELECT @NOME2 = NOME, @DATA2 = [DATA DE NASCIMENTO], @IDADE2 = IDADE 
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF

PRINT @NOME2
PRINT @DATA2
PRINT @IDADE2


-----------------------------------------

DECLARE @IDADE INT
DECLARE @NOME VARCHAR(200)
DECLARE @DATA DATE

DECLARE @IDADE_2 INT, @NOME_2 VARCHAR(200), @DATA_2 DATE

SET @IDADE = 20
PRINT @IDADE

SET @NOME = 'JOSÉ DA SILVA'
PRINT @NOME

SET @DATA = '20180517'
PRINT @DATA


--DECLARANDO A VARIÁVEL E USANDO UM SELECT PARA ATRIBUIR VALOR A VARIÁVEL.

DECLARE @CPF VARCHAR(12)
SET @CPF = '1471156710'

SELECT NOME, DATA_NASCIMENTO, IDADE FROM CLIENTES WHERE CPF = @CPF

SELECT @NOME_2 = NOME, @DATA_2 = DATA_NASCIMENTO, @IDADE_2 = IDADE FROM CLIENTES WHERE CPF = @CPF

PRINT @NOME_2
PRINT @DATA_2
PRINT @IDADE_2

