
CREATE FUNCTION EnderecoCompleto 
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
   DECLARE @ENDERECO_COMPLETO VARCHAR(250)
   SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
   RETURN @ENDERECO_COMPLETO
END

SELECT CPF, [dbo].[EnderecoCompleto]([ENDERECO 1], CIDADE, ESTADO, CEP) AS END_COMPLETO
FROM [TABELA DE CLIENTES]

ALTER FUNCTION EnderecoCompleto 
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20))
RETURNS VARCHAR(250)
AS
BEGIN
   DECLARE @ENDERECO_COMPLETO VARCHAR(250)
   SET @ENDERECO_COMPLETO = @ENDERECO + ', ' + @CIDADE + ', ' + @ESTADO + ', ' + @CEP
   RETURN @ENDERECO_COMPLETO
END

SELECT CPF, [dbo].[EnderecoCompleto]([ENDERECO 1], CIDADE, ESTADO, CEP) AS END_COMPLETO
FROM [TABELA DE CLIENTES]


-------------------------------------------------------------


CREATE FUNCTION EnderecoCompleto
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20)) RETURNS VARCHAR(250)
AS
BEGIN
DECLARE @ENDERECO_COMPLETO VARCHAR(250)
SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
RETURN @ENDERECO_COMPLETO
END

SELECT CPF, [dbo].[EnderecoCompleto](ENDERECO, CIDADE, ESTADO, CEP) AS END_COMPLETO FROM CLIENTES





ALTER FUNCTION EnderecoCompleto
(@ENDERECO VARCHAR(100), @CIDADE VARCHAR(50), @ESTADO VARCHAR(50), @CEP VARCHAR(20)) RETURNS VARCHAR(250)
AS
BEGIN
DECLARE @ENDERECO_COMPLETO VARCHAR(250)
SET @ENDERECO_COMPLETO = @ENDERECO + ', ' + @CIDADE + ' - ' + @ESTADO + ', ' + @CEP
RETURN @ENDERECO_COMPLETO
END


-----------------------------------------------------------
SELECT DATA, COUNT(*) AS NUMERO FROM NOTAS  
    WHERE DATA >= '20150101' AND DATA <= '20150110'
GROUP BY DATA




ALTER FUNCTION FuncTabelaNotas (
    @DATAINICIAL AS DATE, 
    @DATAFINAL AS DATE
) RETURNS TABLE
RETURN SELECT DATA, COUNT(*) AS NUMERO 
    FROM NOTAS WHERE DATA >= @DATAINICIAL AND 
        DATA <= @DATAFINAL 
GROUP BY DATA




SELECT * FROM [dbo].[FuncTabelaNotas]('20150101','20150110')


