SELECT GETDATE()
SELECT DATENAME(WEEKDAY, DATEADD(DAY, 6, GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT
SET @NUMERO_DIAS = 9
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
   PRINT 'Este dia é fim de semana'
ELSE
   PRINT 'Este dia é dia da semana'
   
   
   
   
   ----------------------------------
   
   


SELECT GETDATE() --DATA ATUAL
SELECT DATENAME(WEEKDAY, GETDATE()) --NOME DO DIA ATUAL
SELECT DATENAME(WEEKDAY, DATEADD(DAY, 4, GETDATE())) --PEGA O DIA 4 DIAS A FRENTE


--VERIFICAR SE O DIA É UM DIA DE SEMANA OU FINAL DE SENAMA
DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 2
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))

print @DIA_SEMANA

IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
PRINT 'Final de semana'
ELSE
PRINT 'Dia útil'
