

CREATE PROCEDURE CalculaIdade
AS
BEGIN
   UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE())
END

INSERT INTO CLIENTES (CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES
('123123123','JOÃO MACHADO', 'RUA PROJETADA A','MADUREIRA','Rio de Janeiro','RJ','20000', '20000306','M',120000, 120000, 120000)

SELECT * FROM CLIENTES WHERE CPF = '123123123'

EXEC CalculaIdade


-----------------------------------------------------------

SELECT * FROM NOTAS NF
INNER JOIN ITENS_VENDIDOS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN PRODUTOS TP ON TP.CODIGO = INF.CODIGO
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2015 AND TP.EMBALAGEM = 'Lata'

UPDATE NF SET NF.IMPOSTO = 0.18 FROM NOTAS NF
INNER JOIN ITENS_VENDIDOS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN PRODUTOS TP ON TP.CODIGO = INF.CODIGO
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2015 AND TP.EMBALAGEM = 'Lata'

CREATE PROCEDURE AtualizaImposto @MES AS INT, @ANO AS INT, @EMBALAGEM AS VARCHAR(10), @IMPOSTO AS FLOAT
AS
UPDATE NF SET NF.IMPOSTO = @IMPOSTO FROM NOTAS NF
    INNER JOIN ITENS_VENDIDOS INF 
        ON NF.NUMERO = INF.NUMERO
    INNER JOIN PRODUTOS TP 
        ON TP.CODIGO = INF.CODIGO
    WHERE MONTH(NF.DATA) = @MES AND YEAR(NF.DATA) = @ANO 
        AND TP.EMBALAGEM = @EMBALAGEM

EXEC AtualizaImposto @MES = 2, @ANO = 2017, @EMBALAGEM = 'PET', @IMPOSTO = 0.16

