
SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [PRODUTOS] WHERE [CÓDIGO] = '1000889'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CÓDIGO] = '1000889'

UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE A.[CÓDIGO] = '1000889'


SELECT B.CODIGO_DO_PRODUTO, B.PRECO_DE_LISTA, A.CODIGO, A.PRECO_LISTA
FROM PRODUTOS A INNER JOIN SUCOS_VENDAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHERE A.[CODIGO] = '1000889'


select v.bairro, c.bairro, c.nome, c.volume_de_compra
from vendedores v inner join clientes c on v.bairro = c.bairro

update c set c.volume_de_compra = c.volume_de_compra * 1.30
from clientes c inner join vendedores v on c.bairro = v.bairro