
	 SELECT * from [PRODUTOS] WHERE SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [PRODUTOS] WHERE [CODIGO] = '1001000'

	 SELECT * FROM [PRODUTOS]  WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 DELETE FROM [PRODUTOS] WHERE [TAMANHO] = '1 Litro' AND SUBSTRING([DESCRITOR],1,15) = 'Sabor dos Alpes'

	 SELECT [CODIGO_DO_PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA_DE_PRODUTOS]

	 SELECT * FROM [PRODUTOS] WHERE [CODIGO] NOT IN (SELECT [CODIGO_DO_PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA_DE_PRODUTOS])

	 DELETE FROM [PRODUTOS] WHERE [CODIGO] NOT IN (SELECT [CODIGO_DO_PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA_DE_PRODUTOS])