
ALTER TABLE NOTAS WITH CHECK ADD CONSTRAINT FK_NOTAS_CLIENTES FOREIGN KEY(CPF)
REFERENCES CLIENTES (CPF)

ALTER TABLE NOTAS  WITH CHECK ADD  CONSTRAINT FK_NOTAS_VENDEDORES FOREIGN KEY(MATRICULA)
REFERENCES VENDEDORES (MATRICULA)

ALTER TABLE ITENS_VENDIDOS  WITH CHECK ADD  CONSTRAINT FK_ITENS_VENDIDOS_NOTAS FOREIGN KEY(NUMERO)
REFERENCES NOTAS (NUMERO)

ALTER TABLE ITENS_VENDIDOS  WITH CHECK ADD  CONSTRAINT FK_ITENS_VENDIDOS_PRODUTOS FOREIGN KEY(CODIGO)
REFERENCES PRODUTOS (CODIGO)
