CREATE TABLE PRODUTOS
(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
CONSTRAINT PK_PRODUTOS PRIMARY KEY CLUSTERED (CODIGO)
)


CREATE TABLE VENDEDORES
(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS BIT NULL,
CONSTRAINT PK_VENDEDORES PRIMARY KEY CLUSTERED (MATRICULA)
)


CREATE TABLE CLIENTES
(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(50) NULL,
ENDERECO VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INT NULL,
SEXO VARCHAR(1),
LIMITE_DE_CREDITO FLOAT,
VOLUME_DE_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT,
CONSTRAINT PK_CLIENTES PRIMARY KEY CLUSTERED (CPF)
)


CREATE TABLE NOTAS
(
NUMERO VARCHAR(5) NOT NULL,
[DATA] DATE NULL,
CPF VARCHAR(11) NULL,
MATRICULA VARCHAR(5) NULL,
IMPOSTO FLOAT NULL,
CONSTRAINT PK_NOTAS PRIMARY KEY CLUSTERED (NUMERO)
) 

CREATE TABLE ITENS_VENDIDOS
(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INT NULL,
PRECO FLOAT NULL,
CONSTRAINT PK_ITENS_VENDIDOS PRIMARY KEY CLUSTERED (NUMERO, CODIGO)
) 














