
SELECT * from SUCOS_VENDAS.dbo.TABELA_DE_PRODUTOS

SELECT * from PRODUTOS

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
 FROM SUCOS_VENDAS.DBO.TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO <> '1040107'

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_VENDAS.DBO.TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO <> '1040107'



INSERT INTO CLIENTES (CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
SELECT CPF, NOME, ENDERECO_1, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA
FROM SUCOS_VENDAS.dbo.TABELA_DE_CLIENTES   WHERE CPF <> '1471156710' AND CPF <> '19290992743' AND CPF <> '2600586709'